### ISSUE TITLE
Priority 1 - adapt on windows 7

### ISSUE THREAD

**Issue by noush-h2o** [e-paire/boscnegre-vacances.com#42]
On windows 7 on IE 11, the layout is broken. See attached file
The pictures are blour and all the text isn't well centered.

[Het format van de site lijkt niet goed te kloppen en groter te worden afgebeeld dan bedoeld.docx](https://github.com/boscnegre-vacances/boscnegre-vacances.github.io/files/717825/Het.format.van.de.site.lijkt.niet.goed.te.kloppen.en.groter.te.worden.afgebeeld.dan.bedoeld.docx)

**Comment by xuopled** [comment]
I did small changes but I did not test. Could you check please ?

**Comment by noush-h2o** [comment]
No i don't see anything

**Comment by xuopled** [comment]
Please check

**Comment by noush-h2o** [comment]
It's better but the big picture are blurry 
![Uploading Sans titre.png…]()

**Comment by xuopled** [comment]
I can't see your image

**Comment by noush-h2o** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/23127980/22339144/53470780-e3e9-11e6-8611-97866e665084.png)

**Comment by noush-h2o** [comment]
Pictures are still a  bit blurry

**Comment by xuopled** [comment]
I explained you why
